chore(ci): general maintenance
GetStream/stream-php pull request #110
Opened 2022-04-20 13:49 UTC by peterdeme

2022-04-20 14:10 UTC, peterdeme commented
Holy 💩 , we have a lots of linter errors, I'll need to fix it.

2022-04-20 18:06 UTC, ferhatelmas commented on .github/workflows/ci.yml
> +        if: matrix.php-versions == '7.3'
yes, this is better

2022-04-20 18:07 UTC, ferhatelmas commented on README.md
> +You can sign up for a Stream account at our [Get Started](https://getstream.io/chat/get_started/) page.
this is feed sdk, url is wrong

2022-04-20 18:08 UTC, ferhatelmas commented on README.md
> +You can use this library to access chat API endpoints server-side.
same here

2022-04-20 18:08 UTC, ferhatelmas commented on README.md
> +For the client-side integrations (web and mobile) have a look at the JavaScript, iOS and Android SDK libraries ([docs](https://getstream.io/chat/)).
tweak your intro for feeds

2022-04-20 18:09 UTC, ferhatelmas commented on README.md
feed sdks are BSD-3, don't change it

2022-04-20 18:10 UTC, ferhatelmas commented on composer.json
> -        "ramsey/uuid": "^3.8"
I loved your refactor

2022-04-20 18:12 UTC, ferhatelmas commented on tests/integration/ReactionTest.php
> +
might want to have a test util though

2022-04-20 18:13 UTC, ferhatelmas requested changes
* readme and license updates are wrong
* dropped dep is great but could use a helper to reduce repetition
* rest is good (this will enable us to drop legacy auth easily)

2022-04-20 19:33 UTC, peterdeme commented on README.md
copy-pasta 🍝

2022-04-20 19:33 UTC, peterdeme commented on composer.json
> -        "ramsey/uuid": "^3.8"
🙏

2022-04-21 13:19 UTC, peterdeme commented on README.md
> +You can sign up for a Stream account at our [Get Started](https://getstream.io/chat/get_started/) page.
fixed

2022-04-21 13:19 UTC, peterdeme commented on README.md
> +You can use this library to access chat API endpoints server-side.
fixed

2022-04-21 13:19 UTC, peterdeme commented on README.md
added back

2022-04-22 15:51 UTC, ferhatelmas approved these changes
LGTM

2022-04-22 16:01 UTC, ferhatelmas approved these changes

2022-04-22 16:14 UTC, merged